name: Run Coveralls

on: 
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pip install coveralls pytest
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          pip install coveralls pytest
          coverage run --source=src -m pytest tests/
          coveralls

      - name: Coveralls
        uses: coverallsapp/github-action@v2

